buono<ADJ><masc><sg> % gut
bello<ADJ><masc><sg> % schön
nuovo<ADJ><masc><sg> % neu
vecchio<ADJ><masc><sg> % alt
corto<ADJ><masc><sg> % kurz
forte<ADJ><masc><sg> % stark
forte<ADJ><fem><sg> % stark
debole<ADJ><masc><sg> % schwach
debole<ADJ><fem><sg> % schwach
felice<ADJ><masc><sg> % glücklich
triste<ADJ><fem><sg> % traurig
triste<ADJ><masc><sg> % traurig
gentile<ADJ><fem><sg> % kind
gentile<ADJ><masc><sg> % kind
