buono<ADJ><AdjReg-o>
bello<ADJ><AdjReg-o>
nuovo<ADJ><AdjReg-o>
vecchio<ADJ><AdjReg-o>
corto<ADJ><AdjReg-o>
forte<ADJ><AdjReg-e>
debole<ADJ><AdjReg-e>
felice<ADJ><AdjReg-e>
triste<ADJ><AdjReg-e>
gentile<ADJ><AdjReg-e>
amare<VERB><VerbReg-are>
andare<VERB><VerbReg-are>
accettare<VERB><VerbReg-are>
imparare<VERB><VerbReg-are>
controllare<VERB><VerbReg-are>