Wortart:
Adjectives, Verbs

Flexionklassen:
Adjectives:
case 1: -o, -i, -a, -e (buono, bello, nuovo, vecchio, corto)
case 2: -e, -i, -e, -i (forte, debole, felice, triste, gentile)


Verbs:
1st conjugation: -are (amare, andare, accettare, imparare, controllare)
2nd conjugation: -ere (correre, credere, discutere, dovere, essere)
3rd conjugation: -ire


Source:
https://en.wikipedia.org/wiki/Italian_language
https://en.wikipedia.org/wiki/Italian_grammar#:~:text=di%20%2B%20le-,Inflection%20of%20nouns%20and%20adjectives,is%20the%20opposite%20of%20arbitrary.
https://www.vocabulix.com/conjugation/Italian-Verbs.html
https://tandem.net/blog/italian-adjectives

https://www.cis.lmu.de/~schmid/tools/SMOR/dspin/ch01s03.html#Tags
https://conjugator.reverso.net/conjugation-italian-verb-amare.html
https://conjugator.reverso.net/conjugation-italian-verb-amare.html
